name: Standard worflow

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Runs this workflow"
      - id: step 2
        run: echo "Complete workflow"
