name: Reusable workflow example

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - name: Add file
        run: 'curl -H "Authorization: bearer $TOKEN" -X PUT "https://api.github.com/repos/$REPO/contents/new_file.md" --data ''{"message": "Create new_file", "content": "Ran the reusable workflow!"}'' '
        env:
          TOKEN: ${{ secrets.token }}
          REPO: ${{ inputs.repo_name }} 
